routes/web.php
<?php

Route::get('/', function () {
    return view('home');
});

Route::get('/p/about', function () {
    return view('pages.static.about');
});

Route::get('/home', function () {
    return view('home');
});

Route::get('/p/imprint', function () {
    return view('pages.static.imprint');
});

Route::get('/p/terms', function () {
    return view('pages.static.terms');
});

Route::get('/p/postcards', function () {
    return view('postcards.list');
});

Auth::routes();

Route::get('auth/github', 'Auth\SocialController@redirectToProvider');
Route::get('auth/github/callback', 'Auth\SocialController@handleProviderCallback');

Route::resource('users', 'Users\UserController');
Route::resource('usergroups', 'Meetups\UsergroupController');

Route::get('@{username}', 'Users\UserController@show');

Route::resource('blogs', 'Blog\UserController');
Route::resource('blogs.articles', 'Blog\ArticleController');

Route::get('/profile', 'Profile\ProfileController@index');
Route::get('/settings', 'Profile\SettingsController@index');

Route::post('/updateLocation', 'Intern\Profile\LocationController@updateLocation');
Route::post('/updateAvatar', 'Intern\Profile\AvatarController@updateAvatar');

Route::group(['prefix' => 'backend', 'middleware' => 'admin'], function () {
    Route::get('/', 'Backend\BackendController@index');
    Route::resource('users', 'Backend\Users\UserController');
    Route::resource('articles', 'Backend\Blogs\ArticleController');
    Route::resource('postcards', 'Backend\Postcards\PostcardController');
});

resources/views/_includes/navigation/nav_left.blade.php
<li>
    <a href="{{ url('/') }}">Home</a>
</li>

<li>
    <a href="{{ url('/p/about') }}">About</a>
</li>

<li>
    <a href="{{ url('users') }}">Users</a>
</li>

{{--<li>--}}
    {{--<a href="{{ route('blogs.index') }}">Blogs</a>--}}
{{--</li>--}}

<li>
    <a href="https://larajobs.com/?partner=499">Jobs</a>
</li>

<li>
    <a href="{{ url('/usergroups') }}">Usergroups</a>
</li>

<li>
    <a href="https://phpmapslack.herokuapp.com/">Slack</a>
</li>

{{--<li>--}}
    {{--<a href="{{ url('/p/postcards') }}">Postcards</a>--}}
{{--</li>--}}

resources/views/_includes/navigation/nav_right.blade.php
{{--<li>--}}
    {{--<a href="{{ url('/timeline') }}">Timeline</a>--}}
{{--</li>--}}

@if(auth()->user()->notifications()->count())
<li class="dropdown notifications">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
        <i class="fa fa-bell" aria-hidden="true"></i>
    </a>

    <ul class="dropdown-menu" role="menu">
            @foreach(auth()->user()->notifications as $notification)
                <li>
                    <a href="#">{{ $notification->data }}</a>
                </li>
            @endforeach

            <li class="divider"></li>

            <li>
                <a href="{{ url('/notifications') }}">All Notifications</a>
            </li>
    </ul>
</li>
@endif